baseURL = 'https://romanthapa8848.github.io/mysite/'
languageCode = 'en-us'
title = 'Roman Thapa'
theme = 'roman'
defaultContentLanguage = 'en'
enableRobotsTXT = true
paginate = 10
summaryLength = 70

[params]
  author = "Roman Thapa"
  description = "Welcome to Roman Thapa's blog. Sharing insights, ideas, and inspirations."
  keywords = ["blog", "AI", "technology", "personal branding", "Roman Thapa"]
  showRelatedPosts = true
  dateFormat = "January 2, 2006"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
